---

- name: Instala passlib
  ansible.builtin.apt: 
    update_cache: true
    name:
      - python3-passlib
    state: present
  become: true

- name: Cria o grupo '{{user.group}}'
  ansible.builtin.group:
    name: '{{user.group}}'
    gid: '{{user.guid}}'
    state: present
  become: true

- name: Cria o usuário {{user.login}}
  ansible.builtin.user:
    name: '{{user.login}}'
    comment: '{{user.comment}}'
    uid: '{{user.uid}}'
    password: "{{user.password | password_hash('sha512')}}"
    update_password: on_create
    group: '{{user.group}}'
    groups: '{{user.groups}}'
    shell: /bin/bash
    append: true
    generate_ssh_key: true
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: '/home/{{user.login}}/.ssh/id_rsa'
    ssh_key_passphrase: '{{user.key_password}}'
    force: false
    state: present
  become: true

...