# ansible-playbook -e@tmp/vault-gaio.yaml playbook-instalar.yaml --syntax-check
# Antes de executar, criar um arquivo vault de acordo com o modelo: vault-modelo.yaml
---

- name: Configurar a estação de trabalho
  hosts: localhost 

  roles:
#  - linux-atualizar
#  - linux-home-configurar
#  - linux-home-configurar_painel
#  - linux-network-vpn-configurar
#  - app-vim-instalar
#  - app-terminator-instalar
#  - app-nautilus-instalar
#  - app-dbeaver-instalar
#  - app-visual_studio_code-instalar
#  - app-aqua_data_studio-instalar
#  - app-apache_jmeter-instalar
#  - app-apache_directory_studio-instalar
#  - app-dbwrench-instalar
#  - app-google_chrome-instalar
#  - app-pgadmin4-instalar
#  - app-firefox-instalar
#  - app-nomachine-instalar
#  - app-vmware_remote_console-instalar
#  - app-synergy-instalar
#  - app-jbosseap7.1-cli-instalar
#  - app-jbosseap6.4-cli-instalar
#  - app-bb_warsaw-instalar
#  - app-downloadhelper_coapp-instalar

...