# ansible-playbook -e@tmp/vault-notebook.yaml playbook-restaurar.yaml --syntax-check
# Antes de executar, criar um arquivo vault de acordo com o modelo: vault-modelo.yaml
---

- name: Configurar a estação de trabalho
  hosts: localhost 

  roles:
#  - linux-atualizar
#  - linux-home-restaurar
#  - linux-network-vpn-restaurar
#  - app-apache_directory_studio-restaurar
#  - app-apache_jmeter-restaurar
#  - app-aqua_data_studio-restaurar
#  - app-dbeaver-restaurar
#  - app-dbwrench-restaurar
#  - app-firefox-restaurar
#  - app-google_chrome-restaurar
#  - app-libreoffice-restaurar
#  - app-nautilus-restaurar
#  - app-pgadmin4-restaurar
#  - app-spotify-restaurar
#  - app-terminator-restaurar
#  - app-thunderbird-restaurar
#  - app-vim-restaurar
#  - app-virtual_box-restaurar
#  - app-visual_studio_code-restaurar
#  - app-nomachine-restaurar
#  - app-synergy-restaurar

...