# ansible-playbook -e@tmp/vault-gaio.yaml playbook-instalar.yaml --syntax-check
# Antes de executar, criar um arquivo vault de acordo com o modelo: vault-modelo.yaml
---

- name: Configurar a estação de trabalho
  hosts: localhost 

  roles:
  - linux-atualizar
  - linux-home-configurar
  - linux-home-configurar_painel
  - linux-network-vpn-configurar
  - app-apache_directory_studio-instalar
  - app-apache_jmeter-instalar
  - app-aqua_data_studio-instalar
  - app-bb_warsaw-instalar
  - app-dbeaver-instalar
  - app-dbwrench-instalar
  - app-downloadhelper_coapp-instalar
  - app-firefox-instalar
  - app-google_chrome-instalar
  - app-jbosseap6.4-cli-instalar
  - app-jbosseap7.1-cli-instalar
  - app-nautilus-instalar
  - app-nomachine-instalar
  - app-pgadmin4-instalar
  - app-spotify-instalar
  - app-synergy-instalar
  - app-terminator-instalar
  - app-vim-instalar
  - app-virtual_box-instalar
  - app-visual_studio_code-instalar
  - app-vlc-instalar
  - app-vmware_remote_console-instalar

...