---

- name: Instala o Vlc
  ansible.builtin.apt: 
    update_cache: true
    name:
      - vlc 
    state: present
  become: true

- name: Restaura o backup
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    sources:
      - '.config/vlc/'
      - '.local/share/vlc/'
  when: restaurar_backup

...