---

- name: Instala e configura o spotify client
  block:

  - name: Adiciona a chave do repositório
    ansible.builtin.apt_key:
      url: '{{app.spotify.key.uri}}/{{app.spotify.key.file}}'
      keyring: '/etc/apt/trusted.gpg.d/{{app.spotify.key.file}}'
      state: present

  - name: Adiciona o repositório
    ansible.builtin.apt_repository:
      repo: 'deb [signed-by=/etc/apt/trusted.gpg.d/{{app.spotify.key.file}}] {{app.spotify.repository}}'
      filename: spotify.list
      state: present

  - name: Instala o spotify-client
    ansible.builtin.apt:
      update_cache: true
      name: spotify-client
      state: present

  become: true

- name: Restaura o backup
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    sources:
      - '.config/spotify/'
  when: restaurar_backup

...