---

- name: Instala e configura o Apache Directory Studio
  block:

  - name: 'Instala as dependências (jdk)'
    ansible.builtin.apt: 
      update_cache: true
      name: default-jdk
      state: present
    become: true

  - name: Baixa o aquivo compactado
    block:

    - name: Verifica se o arquivo existe
      ansible.builtin.stat:
        path: '{{app.directory_studio.path_download}}/{{app.directory_studio.file}}'
      register: file_status

    - name: Cria o diretório '{{app.directory_studio.path_download}}'
      ansible.builtin.file:
        path: '{{downloads_path}}/apache/apache_directory_studio'
        state: directory
        recurse: true
      when: not file_status.stat.exists

    - name: Baixa o arquivo
      ansible.builtin.get_url:
        url: '{{app.directory_studio.uri}}/{{app.directory_studio.file}}'
        dest: '{{app.directory_studio.path_download}}/{{app.directory_studio.file}}'
        decompress: false
        owner: '{{user.login}}'
        group: '{{user.group}}'
        mode: '0644'
      when: not file_status.stat.exists

  - name: Cria a pasta /opt/apache
    ansible.builtin.file:
      path: /opt/apache
      owner: root
      group: root
      mode: '0755'
      state: directory 
    become: true

  - name: 'Descompacta o pacote {{app.directory_studio.file}}'
    ansible.builtin.unarchive:
      src: '{{app.directory_studio.path_download}}/{{app.directory_studio.file}}'
      dest: /opt/apache
      copy: false 
      owner: root
      group: root
    become: true

  - name: Configura o item de menu (Launcher)
    ansible.builtin.include_role:
      name: common
      tasks_from: create_launcher.yaml
    vars: 
      user_login: '{{user.login}}'
      app_launch_name: 'apache-directory-studio'
      app_name: 'Apache Directory Studio'
      app_comment: ''
      app_icon: /opt/apache/ApacheDirectoryStudio/icon.xpm
      app_exec: /opt/apache/ApacheDirectoryStudio/ApacheDirectoryStudio

- name: Restaura o backup
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    sources:
      - '.ApacheDirectoryStudio/'
  when: restaurar_backup

...
