---

- name: Instala e configura o Virtual Box
  block:

    - name: adiciona a chave do repositório
      ansible.builtin.apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg
        state: present
      become: true

    - name: adiciona o repositório
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/virtualbox.gpg] https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib'
        filename: virtualbox.list
        state: present
      become: true
      
    - name: instala o Virtual Box
      ansible.builtin.apt: 
        update_cache: true
        name: virtualbox-7.0
        state: present
      become: true

...