---

- name: Instala e configura o Virtual Box
  block:

    - name: adiciona a chave do reposit칩rio
      ansible.builtin.apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg
        state: present
      become: true

    - name: adiciona o reposit칩rio
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/virtualbox.gpg] https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib'
        filename: virtualbox.list
        state: present
      become: true
      
    - name: instala o Virtual Box
      ansible.builtin.apt: 
        update_cache: true
        name: virtualbox-7.0
        state: present
      become: true

    - name: Adiciona o usu치rio no grupo vboxusers
      ansible.builtin.user:
        name: '{{user.login}}'
        groups: 'vboxusers'
        append: true
      become: yes

- name: Restaura os diret칩rios do VirtualBox
  ansible.builtin.copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    local_follow: true
    mode: preserve
    owner: '{{user.login}}'
    group: '{{user.group}}'
  with_items:
    - {src: '{{path_to_backup}}/home/{{user.login}}/.config/VirtualBox/', dest: '/home/{{user.login}}/.config/VirtualBox/'}
    - {src: '{{path_to_backup}}/u01/virtual_machines/', dest: '/u01/virtual_machines/'}
    - {src: '{{path_to_backup}}/u02/virtual_machines/', dest: '/u02/virtual_machines/'}
  when: restaurar_backup

...