---

- name: Instala e configura o Virtual Box
  block:

    - name: Adiciona a chave do reposit칩rio
      ansible.builtin.get_url:
        url: '{{app.virtualbox.key.uri}}/{{app.virtualbox.key.file}}'
        dest: '/etc/apt/keyrings/{{app.virtualbox.key.file}}'
      become: true

    - name: adiciona o reposit칩rio
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=//etc/apt/keyrings/{{app.virtualbox.key.file}}] {{app.virtualbox.repository}}'
        filename: virtualbox.list
        state: present
      become: true

    - name: instala o Virtual Box
      ansible.builtin.apt: 
        update_cache: true
        name: virtualbox-7.0
        state: present
      become: true

    - name: Adiciona o usu치rio no grupo vboxusers
      ansible.builtin.user:
        name: '{{user.login}}'
        groups: 'vboxusers'
        append: true
      become: yes

- name: Restaura os diret칩rios do VirtualBox
  ansible.builtin.copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    local_follow: true
    mode: preserve
    owner: '{{user.login}}'
    group: '{{user.group}}'
  with_items:
    - {src: '{{backup_path}}/home/{{user.login}}/.config/VirtualBox/', dest: '/home/{{user.login}}/.config/VirtualBox/'}
    - {src: '{{backup_path}}/u01/virtual_machines/', dest: '/u01/virtual_machines/'}
    - {src: '{{backup_path}}/u02/virtual_machines/', dest: '/u02/virtual_machines/'}
  when: restaurar_backup

...
