---

- name: Instala o Vim
  ansible.builtin.apt: 
    update_cache: true
    name:
      - vim 
    state: present
  become: true

- name: Configura o vim como o editor padrão de linha de comando
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim.basic
    state: selected
  become: true

- name: Configura as preferências do vim (.vimrc)
  ansible.builtin.copy:
    src: vimrc
    dest: /home/{{user.login}}/.vimrc
    local_follow: false
    mode: preserve
    owner: '{{user.login}}'
    group: '{{user.group}}'

- name: Restaura os arquivos e pastas de configuração
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    soures:
      - '.vimrc'
  when: restaurar_backup

...