---

- name: Instala e configurar o nomachine
  block:

    - name: Baixa o pacote deb
      block:

        - name: Verifica se o pacote já foi baixado
          ansible.builtin.stat:
            path: '{{app.nomachine.download_path}}/{{app.nomachine.file}}'
          register: file_status

        - name: Baixa o pacote
          ansible.builtin.get_url:
            url: '{{app.nomachine.uri}}/{{app.nomachine.file}}'
            dest: '{{app.nomachine.download_path}}/{{app.nomachine.file}}'
            owner: '{{user.login}}'
            group: '{{user.group}}'
            mode: '0644'
          when: not file_status.stat.exists

        - name: Instala o nomachine
          ansible.builtin.apt: 'deb={{app.nomachine.download_path}}/{{app.nomachine.file}}'

  become: true

- name: Restaura o backup
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    sources:
      - '.nx/'
  when: restaurar_backup

...
