---

- name: Restaura os arquivos e pastas de configuração
  ansible.builtin.import_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    soures:
      - '.config/libreoffice/'

...