---

- name: 'Cria os diretórios /u01 e /u02'
  ansible.builtin.file:
    path: '{{item}}'
    state: directory
    recurse: true
    owner: '{{user.login}}'
    group: '{{user.group}}'
  become: true
  with_items:
    - '/u01'
    - '/u02'

- name: Restaura os diretórios do VirtualBox
  ansible.builtin.copy:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    local_follow: true
    mode: preserve
    owner: '{{user.login}}'
    group: '{{user.group}}'
  with_items:
    - {src: '{{path_to_backup}}/home/{{user.login}}/.config/VirtualBox/', dest: '/home/{{user.login}}/.config/VirtualBox/'}
    - {src: '{{path_to_backup}}/u01/virtual_machines/', dest: '/u01/virtual_machines/'}
    - {src: '{{path_to_backup}}/u02/virtual_machines/', dest: '/u02/virtual_machines/'}

...