---

- name: Instala e configura o Dbeaver
  block:

    - name: Adiciona a chave do repositório
      ansible.builtin.get_url:
        url: '{{app.dbeaver.key.uri}}/{{app.dbeaver.key.file}}'
        dest: '/etc/apt/keyrings/{{app.dbeaver.key.file}}'
      become: true

    - name: Adiciona o repositório
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/etc/apt/keyrings/{{app.dbeaver.key.file}}] {{app.dbeaver.repository}}'
        filename: dbeaver-ce
        state: present
      become: true

    - name: Instala o DBeaver
      ansible.builtin.apt: 
        update_cache: true
        name:
          - default-jdk
          - dbeaver-ce
        state: present
      become: true

- name: Restaura o backup
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    sources:
      - '.local/share/DBeaverData/'
      - 'applications/jdbc/'
  when: restaurar_backup

...
