---

- name: Configura os itens do painel 
  community.general.xfconf: channel='{{item.channel}}' property='{{item.property}}' value_type='{{item.value_type}}' value='{{item.value}}' state='{{item.state}}'
  with_items:
    # separator
    - {channel: 'xfce4-panel', property: '/plugins/plugin-4/expand', value_type: 'bool', value: 'true', state: 'present'}
    # indicator
    - {channel: 'xfce4-panel', property: '/plugins/plugin-7', value_type: 'string', value: 'indicator', state: 'absent'}
    # power-manager-plugin
    - {channel: 'xfce4-panel', property: '/plugins/plugin-8', value_type: 'string', value: 'power-manager-plugin', state: 'absent'}
    # clock
    - {channel: 'xfce4-panel', property: '/plugins/plugin-10/digital-format', value_type: 'string', value: '%A %Y-%m-%d %H:%M:%S', state: 'present'}
    - {channel: 'xfce4-panel', property: '/plugins/plugin-10/mode', value_type: 'uint', value: '2', state: 'present'}
    # pager (Workspace Switcher)
    - {channel: 'xfce4-panel', property: '/plugins/plugin-11', value_type: 'string', value: 'pager', state: 'present'}
    - {channel: 'xfce4-panel', property: '/plugins/plugin-11/rows', value_type: 'uint', value: '1', state: 'present'}
    # showdesktop
    - {channel: 'xfce4-panel', property: '/plugins/plugin-12', value_type: 'string', value: 'showdesktop', state: 'present'}
    # places
    - {channel: 'xfce4-panel', property: '/plugins/plugin-13', value_type: 'string', value: 'places', state: 'present'}
    - {channel: 'xfce4-panel', property: '/plugins/plugin-13/show-recent', value_type: 'bool', value: 'false', state: 'present'}
    # separator
    - {channel: 'xfce4-panel', property: '/plugins/plugin-14', value_type: 'string', value: 'separator', state: 'present'}
    - {channel: 'xfce4-panel', property: '/plugins/plugin-14/expand', value_type: 'bool', value: 'true', state: 'present'}
    - {channel: 'xfce4-panel', property: '/plugins/plugin-14/style', value_type: 'uint', value: '0', state: 'present'}
    # painel
    #- {channel: 'xfce4-panel', property: '/panels/panel-0/mode', value_type: 'int', value: '0', state: 'present'}
    #- {channel: 'xfce4-panel', property: '/panels/panel-0/size', value_type: 'int', value: '24', state: 'present'}
  notify:
    - reiniciar_painel

- name: Ordena os itens do painel
  community.general.xfconf:
    channel: 'xfce4-panel'
    property: '/panels/panel-0/plugin-ids'
    value_type: 'int'
    value: ['1', '2', '11', '12', '13', '4', '3', '14', '5', '6', '9', '10']
    force_array: true
  notify:
    - reiniciar_painel

...