---

- name: Instala e configura o jboss-cli do eap 7.1
  block:

    - name: Instala as dependências (openjdk8)
      ansible.builtin.apt: 
        update_cache: true
        name: openjdk-8-jdk
        state: present

    - name: 'Cria a pasta /opt/redhat'
      ansible.builtin.file:
        path: /opt/redhat
        owner: root
        group: root
        mode: '0755'
        state: directory

    - name: 'Descompacta o pacote jboss-eap-7.1.0.zip'
      ansible.builtin.unarchive:
        src: '{{path_to_downloads}}/redhat/jboss-eap-7.1.0.zip'
        dest: '/opt/redhat'
        copy: false
        owner: root
        group: root

    - name: 'Configura o JAVA_HOME no script jboss-cli.sh'
      ansible.builtin.lineinfile:
        path: '/opt/redhat/jboss-eap-7.1/bin/jboss-cli.sh'
        line: 'JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"'
        insertbefore: '# Setup JBOSS_HOME'
        backup: true
        state: present

  become: true

- name: 'Cria o atalho'
  ansible.builtin.lineinfile:
    path: '/home/{{user.login}}/.bash_aliases'
    line: 'alias jboss-cli=/opt/redhat/jboss-eap-7.1/bin/jboss-cli.sh'
    backup: true
    create: true
    state: present
  notify:
    - reiniciar_bashrc

...