---

- name: Instala o Synergy
  block:

    - name: Verifica se o pacote existe
      ansible.builtin.stat:
        path: '{{app.synergy.download_path}}/{{app.synergy.file}}'
      register: file_status

    - name: Instala se o pacote existir
      ansible.builtin.apt: 'deb={{app.synergy.download_path}}/{{app.synergy.file}}'
      when: file_status.stat.exists

  become: true

- name: Restaura o backup
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    sources:
      - '.config/synergy/'
      - '.config/Synergy/'
  when: restaurar_backup

...