---

- name: Instala o Synergy
  block:

    - name: Verifica se o pacote existe
      ansible.builtin.stat:
        path: '{{path_to_downloads}}/symless/synergy-linux_x64-libssl3-v3.0.73.7-rc2.deb'
      register: file_status

    - name: Instala se o pacote existir
      ansible.builtin.apt: 'deb={{path_to_downloads}}/symless/synergy-linux_x64-libssl3-v3.0.73.7-rc2.deb'
      when: file_status.stat.exists

  become: true

- name: Restaura os arquivos e pastas de configuração
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    soures:
      - '.config/synergy/'
      - '.config/Synergy/'
  when: restaurar_backup

...