---

- name: Restaura o /etc/hosts
  ansible.builtin.copy:
    src: '{{path_to_backup}}/etc/hosts'
    dest: /etc/hosts
    mode: preserve
    owner: root
    group: root
  become: true

- name: 'Restaura a pasta applications/scripts'
  block:

    - name: 'Restaura a pasta applications/scripts'
      ansible.builtin.copy:
        src: '{{path_to_backup}}/home/{{user.login}}/applications/scripts/'
        dest: '/home/{{user.login}}/applications/scripts/'
        mode: preserve
        owner: '{{user.login}}'
        group: '{{user.group}}'

    - name: Cria o alias para os scripts
      ansible.builtin.lineinfile:
        path: '/home/{{user.login}}/.bash_aliases'
        line: '{{item}}'
        backup: true
        create: true
        state: present
      with_items:
        - 'alias c=~/applications/scripts/conectar.sh'
        - 'alias backup.sh=~/applications/scripts/backup.sh'
      notify: 
        - reiniciar_bashrc

- name: Restaura a chave do usuário
  block:

  - name: Copia as chaves
    ansible.builtin.copy:
      src: '{{path_to_backup}}/home/{{user.login}}/.ssh/'
      dest: '/home/{{user.login}}/.ssh/'
      owner: '{{user.login}}'
      group: '{{user.group}}'
      mode: 0600

  - name: Altera as permissões da pasta .ssh 
    ansible.builtin.file:
      path: '/home/{{user.login}}/.ssh/'
      owner: '{{user.login}}' 
      group: '{{user.group}}'
      mode: 0700 
      state: directory 

- name: 'Configura o background'
  block:

    - name: 'Cria o diretório /home/{{user.login}}/applications'
      ansible.builtin.file:
        path: '/home/{{user.login}}/applications'
        state: directory
        recurse: true
        owner: '{{user.login}}'
        group: '{{user.group}}'
      become: true

    - name: 'Restaura o arquivo /home/{{user.login}}/applications/background'
      ansible.builtin.copy:
        src: '{{path_to_backup}}/home/{{user.login}}/applications/background/'
        dest: '/home/{{user.login}}/applications/background/'
        local_follow: false
        mode: preserve
        owner: '{{user.login}}'
        group: '{{user.group}}'

    - name: 'Seleciona a imagem de backgrund'
      community.general.xfconf: 
        channel: 'xfce4-desktop'
        property: '/backdrop/screen0/monitor0/image-path'
        value_type: 'string'
        value: '/home/{{user.login}}/applications/background/56014-1.jpg'

    - name: 'Aplica a imagem para todos os desktops'
      community.general.xfconf: 
        channel: 'xfce4-desktop'
        property: '/backdrop/single-workspace-mode'
        value_type: 'bool'
        value: true

...