---

- name: Instala e configura o Visual Studio Code
  block:

    - name: adiciona a chave do repositório
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: /etc/apt/keyrings/microsoft.asc
      become: true

    - name: adiciona o repositório
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.asc] https://packages.microsoft.com/repos/vscode stable main'
        state: present
      become: true
      
    - name: instala o Visual Studio Code
      ansible.builtin.apt: 
        update_cache: true
        name:
          - code
          - git
        state: present
      become: true

- name: Restaura os arquivos e pastas de configuração
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    soures:
      - '.config/Code/'
  when: restaurar_backup

...