---

- name: Instala e configura o Visual Studio Code
  block:

    - name: adiciona a chave do repositório
      ansible.builtin.get_url:
        url: '{{app.vscode.key.uri}}/{{app.vscode.key.file}}'
        dest: /etc/apt/keyrings/{{app.vscode.key.file}}
      become: true

    - name: adiciona o repositório
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/{{app.vscode.key.file}}] {{app.vscode.repository}}'
        state: present
      become: true

    - name: instala o Visual Studio Code
      ansible.builtin.apt: 
        update_cache: true
        name:
          - code
          - git
        state: present
      become: true

- name: Restaura o backup
  ansible.builtin.include_role:
    name: common
    tasks_from: restore_configuration_files.yaml
  vars:
    sources:
      - '.config/Code/'
  when: restaurar_backup

...
