---

- name: Verifica se o arquivo existe
  ansible.builtin.stat:
    path: '{{app.downloadhelper.download_path}}/{{app.downloadhelper.file}}'
  register: file_status

- name: Baixa o arquivo
  ansible.builtin.get_url:
    url: '{{app.downloadhelper.uri}}/{{app.downloadhelper.file}}'
    dest: '{{app.downloadhelper.download_path}}/{{app.downloadhelper.file}}'
    decompress: false
    owner: '{{user.login}}'
    group: '{{user.group}}'
    mode: '0644'
  when: not file_status.stat.exists

- name: Instala o DownloadHelper
  ansible.builtin.apt: 
    deb: '{{app.downloadhelper.download_path}}/{{app.downloadhelper.file}}'
  become: true

...