---

- name: reiniciar_NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
  become: true

- name: reiniciar_bashrc
  ansible.builtin.shell:
    cmd: source /home/{{user.login}}/.bashrc

...